name: PR Code Quality Check and Auto-Merge

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disable shallow clones for better relevancy of analysis
  auto-merge:
    name: Auto Merge PR
    needs: sonarcloud
    # Only run auto-merge on pull requests, not pushes to master
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Enable Auto-merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge --delete-branch --repo ${{ github.repository }}
